# simple-theme by ben 
# https://github.com/benTheBike/simple-theme
# https://ben.bike/dev/hexo-themes/simple-theme

# Also see the "variables" section at the top of /source/css/styles.css for changing things like accent-color.

# Items that appear in the navbar.
# Format:   item_title: /url/
navbar_items:
  Home: /
  Blog: /blog
  Projects: /dev
  Search: /search

# Link to a CSS theme to use with highlight js. If nothing is supplied, default will be used.
# Preview - https://highlightjs.org/static/demo/
# CDN - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/theme-name.min.css
# 
hljs_css: "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/atelier-lakeside-dark.min.css"

# Comments
# Using Gitment (https://github.com/imsun/gitment)
comments:
  client_id: 50c34a9ae0a1140b7a94
  client_secret: 3eb5713ac5e8eb098bf067ec31ff8465880cacf6